export const TOWNS = [
  "Ames, IA",
  "Amherst, MA",
  "Ann Arbor, MI",
  "Athens, GA",
  "Berkeley, CA",
  "Binghamton, NY",
  "Blacksburg, VA",
  "Bloomington, IL",
  "Bloomington, IN",
  "Boulder, CO",
  "Bozeman, MT",
  "Burlington, VT",
  "Cambridge, MA",
  "Champaign-Urbana, IL",
  "Chapel Hill, NC",
  "Charlottesville, VA",
  "Claremont, CA",
  "College Station, TX",
  "Columbia, MO",
  "Corvallis, OR",
  "East Lansing, MI",
  "Eugene, OR",
  "Fargo, ND",
  "Fayetteville, AR",
  "Flagstaff, AZ",
  "Fort Collins, CO",
  "Gainesville, FL",
  "Grand Forks, ND",
  "Hartford, CT",
  "Iowa City, IA",
  "Ithaca, NY",
  "Lafayette, IN",
  "Lawrence, KS",
  "Lexington, KY",
  "Lincoln, NE",
  "Logan, UT",
  "Madison, WI",
  "Manhattan, KS",
  "Minneapolis, MN",
  "Morgantown, WV",
  "Oxford, MS",
  "Pittsburgh, PA",
  "San Luis Obispo, CA",
  "State College, PA",
  "Syracuse, NY",
  "Tacoma, WA",
  "Tallahassee, FL",
  "Tempe, AZ",
  "Tuscaloosa, AL",
  "Waterloo-Cedar Falls, IA"
].sort();

export const HOUSE_TYPES = ["Single Family", "Multi Family", "Multiple Occupancy"];


