export const UNIVERSITIES = [
  "Bringhamton University",
  "California Polytechnic State University San Luis Obispo",
  "Colorado State University",
  "Cornell University",
  "Florida State University",
  "Harvard University",
  "Illinois State university",
  "Indiana University Bloomington",
  "Iowa State University",
  "Kansas State University",
  "Michigan State University",
  "Montana State university",
  "North Dakota State University",
  "Northern Arizona University",
  "Oregon State university",
  "Pennsylvania State University",
  "Pomona College",
  "Purdue University",
  "Syracuse University",
  "Texas A&M University",
  "University Kentucky",
  "University of Alabama",
  "University of Arkansas",
  "University of California Berkeley",
  "University of Colorado Boulder",
  "University of Florida",
  "University of Georgia",
  "University of Hartford",
  "University of Illinois at Urbana-Champaign",
  "University of Iowa",
  "University of Kansas",
  "University of Massachusetts Amherst",
  "University of Michigan",
  "University of Minnesota",
  "University of Mississippi",
  "University of Missouri",
  "University of Nebraska Lincoln",
  "University of North Carolina at Chapel Hill",
  "University of North Dakota",
  "University of Northern Iowa",
  "University of Oregon",
  "University of Pittsburgh",
  "University of Vermont",
  "University of Virginia",
  "University of Washington Tacoma",
  "University of Wisconsin Madison",
  "Utah State University",
  "Virginia Tech",
  "West Virginia University"
].sort();

export const HOUSE_TYPES = ["Single Family", "Multi Family", "Multiple Occupancy"];

